apiVersion: apps/v1
kind: Deployment
metadata:
  name: heronsocialmedia-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: heronsocialmedia-frontend
  template:
    metadata:
      labels:
        app: heronsocialmedia-frontend
    spec:
      containers:
        - name: frontend
          image: manulperera5665/heronsocialmedia-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10

