apiVersion: v1
kind: Service
metadata:
  name: heronsocialmedia-frontend
spec:
  selector:
    app: heronsocialmedia-frontend
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80