name: Build and Deploy frontend

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: manulperera5665/heronsocialmedia-frontend
  IMAGE_TAG: ${{ github.sha }}
  FULL_IMAGE_NAME: manulperera5665/heronsocialmedia-frontend:${{ github.sha }}
  KUBE_DEPLOYMENT: heronsocialmedia-frontend
  KUBE_NAMESPACE: default
  CONTAINER_NAME: heronsocialmedia-frontend

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show files (debug)
        run: Get-ChildItem -Force
        shell: powershell

      - name: Docker login to Docker Hub
        run: docker login -u $env:DOCKERHUB_USERNAME -p $env:DOCKERHUB_TOKEN
        shell: powershell
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: docker build -t $env:FULL_IMAGE_NAME .
        shell: powershell

      - name: Push Image to Docker Hub
        run: docker push $env:FULL_IMAGE_NAME
        shell: powershell

      - name: Update Kubernetes Deployment Image
        run: kubectl set image deployment/$env:KUBE_DEPLOYMENT $env:CONTAINER_NAME=$env:FULL_IMAGE_NAME -n $env:KUBE_NAMESPACE
        shell: powershell
